repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v2.3.0
#     hooks:
#     -   id: flake8
#     -   id: check-yaml
#     -   id: end-of-file-fixer
#     -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    -   id: mypy
        files: ^(python/src/|python/tests/)
        args: []
